version: '3.8'

services:
  db:
    env_file: ./.env
    container_name: ${MYSQLDB_HOST}
    image: mysql:latest
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQLDB_ROOT_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    ports:
      - ${MYSQLDB_PORT}:${MYSQLDB_PORT}
    volumes:
      - dbdata:/var/lib/mysql
    command: ['mysqld','--sql-mode=', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_bin', '--skip-character-set-client-handshake']

  app:
    env_file: ./.env
    container_name: rf4
    build: .
    restart: unless-stopped
    ports:
      - ${SPRING_PORT}:${SPRING_PORT}
    depends_on:
      db:
        condition: service_healthy    

volumes:
  indexdata:
  dbdata: